// frontend/src/pages/WorkflowEditorPage/index.tsx
import React, { useEffect } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import './index.less';
import { useParams, useLocation } from 'react-router-dom';
import { App as AntApp } from 'antd';
import '../../components/TaskNode'; // Register custom node
import EditorDagGraph from './components/EditorDagGraph';
import { WorkflowToolbar } from './components/WorkflowToolbar';
import EditTaskModal from './components/EditTaskModal';
import EditParamNodeModal from './components/EditParamNodeModal';
import EditEdgeLabelModal from './components/EditEdgeLabelModal';
import { ViewYamlModal } from './components/ViewYamlModal';
import { WorkflowContextMenu } from './components/WorkflowContextMenu';
import { RootState, AppDispatch } from '../../store';
import {
  setContextMenu,
  fetchDiyFunctions,
  fetchWorkflow,
  setWorkflowData,
  clearWorkflow,
} from '../../store/slices/workflowEditorSlice';
import { WorkflowDetail } from '../../types';



const WorkflowEditorPage: React.FC = () => {
  const dispatch: AppDispatch = useDispatch();
  const location = useLocation();
  const { workflow_uuid } = useParams<{ workflow_uuid: string }>();
  const { message } = AntApp.useApp();

  const {
    contextMenu,
  } = useSelector((state: RootState) => state.workflowEditor);

  useEffect(() => {
    dispatch(fetchDiyFunctions()).unwrap().catch(() => message.error('加载自定义组件失败'));

    if (workflow_uuid) {
      dispatch(fetchWorkflow(workflow_uuid)).unwrap().catch(() => message.error('加载工作流数据失败。'));
    } else {
      dispatch(clearWorkflow());
      const searchParams = new URLSearchParams(location.search);
      const projectName = searchParams.get('projectName');
      const projectCode = searchParams.get('projectCode');
      if (projectName && projectCode) {
        const initialWorkflowData: WorkflowDetail = {
          code: 0,
          name: 'new-workflow',
          uuid: '',
          project: projectName,
          projectCode: parseInt(projectCode, 10),
          projectName: projectName,
          releaseState: 'UNSUBMITTED',
          updateTime: '',
          schedule_text: '',
          schedule_human_readable: '',
          tasks: [],
          parameters: [],
          relations: [],
          filename: '',
          yaml_content: '',
          locations: '',
          schedule: '',
          local_status: 'new',
        };
        dispatch(setWorkflowData(initialWorkflowData));
      }
    }
  }, [workflow_uuid, message, dispatch, location.search]);




  return (
    <div style={{ display: 'flex', height: 'calc(100vh - 64px)' }}>
      <div style={{ flex: 1, position: 'relative' }} onClick={() => dispatch(setContextMenu({ ...contextMenu, visible: false }))}>
        <WorkflowToolbar />
        <EditorDagGraph />
        <EditTaskModal />
        <EditParamNodeModal />
        <EditEdgeLabelModal />
        <ViewYamlModal />
        <WorkflowContextMenu />
      </div>
    </div>
  );
};

export default WorkflowEditorPage;

// frontend-vue/src/pages/WorkflowEditorPage/index.vue
<template>
  <div style="display: flex; height: calc(100vh - 64px)">
    <div style="flex: 1; position: relative" @click="handleContainerClick">
      <!-- <WorkflowToolbar @import="handleImport" /> -->
      <!-- <EditorDagGraph :container-ref="containerRefCallback" /> -->
      <!-- <EditTaskModal /> -->
      <!-- <EditParamNodeModal /> -->
      <!-- <EditEdgeLabelModal /> -->
      <!-- <ViewYamlModal /> -->
      <!-- <WorkflowContextMenu /> -->
      <div ref="containerRef">
        工作流编辑器占位符
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, computed } from 'vue';
import { useStore } from 'vuex';
import { useRoute } from 'vue-router';
import { App as AntApp } from 'ant-design-vue';
import { State as RootState } from '../../store';
import { WorkflowDetail } from '../../types';

const store = useStore<RootState>();
const route = useRoute();
const { message } = AntApp.useApp();

const containerRef = ref<HTMLDivElement | null>(null);

const contextMenu = computed(() => store.state.workflowEditor.contextMenu);

onMounted(() => {
  if (containerRef.value) {
    store.dispatch('workflowEditor/initializeGraph', containerRef.value);
  }

  store.dispatch('workflowEditor/fetchDiyFunctions').catch(() => message.error('加载自定义组件失败'));

  const workflowUuid = route.params.uuid as string;
  if (workflowUuid) {
    store.dispatch('workflowEditor/fetchWorkflow', workflowUuid);
  } else {
    store.dispatch('workflowEditor/clearWorkflow');
    const { projectName, projectCode } = route.query;
    if (projectName && projectCode) {
      const initialWorkflowData: Partial<WorkflowDetail> = {
        name: 'new-workflow',
        project: projectName as string,
        projectCode: parseInt(projectCode as string, 10),
        projectName: projectName as string,
        releaseState: 'UNSUBMITTED',
        tasks: [],
        parameters: [],
        relations: [],
        yaml_content: '',
      };
      store.commit('workflowEditor/setWorkflow', initialWorkflowData);
    }
  }
});

const handleContainerClick = () => {
  store.commit('workflowEditor/setContextMenu', { ...contextMenu.value, visible: false });
};

// Placeholder for import handling
// const handleImport = (file: File) => {
//   store.dispatch('workflowEditor/importYaml', file).catch(() => message.error('导入 YAML 失败'));
// };
</script>

<style scoped>
/* Add styles from index.less if necessary */
</style>
