// frontend-vue/src/App.tsx
import React from 'react';
import { BrowserRouter as Router, Routes, Route, Link, useLocation } from 'react-router-dom';
import { App as AntApp, Layout, Menu, ConfigProvider, Typography } from 'antd';
import { DashboardOutlined, ApartmentOutlined, CodeOutlined } from '@ant-design/icons';
import zhCN from 'antd/locale/zh_CN';

import WelcomePage from './pages/WelcomePage';
import HomePage from './pages/HomePage';
import DashboardPage from './pages/DashboardPage';
import WorkflowEditorPage from './pages/WorkflowEditorPage';
import WorkflowViewerPage from './pages/WorkflowViewerPage';
import WorkflowHistoryPage from './pages/WorkflowHistoryPage';
import DiyFunctionPage from './pages/DiyFunctionPage';
import PythonEditorPage from './pages/PythonEditorPage';
import WorkflowInstanceDetailPage from './pages/WorkflowInstanceDetailPage';
import './App.css';

const { Header, Content, Sider } = Layout;
const { Title } = Typography;

const App: React.FC = () => {
  const location = useLocation();

  const menuItems = [
    {
      key: '/',
      icon: <DashboardOutlined />,
      label: <Link to="/">欢迎页</Link>,
    },
    {
      key: '/dashboard',
      icon: <DashboardOutlined />,
      label: <Link to="/dashboard">仪表盘</Link>,
    },
    {
      key: '/workflows',
      icon: <ApartmentOutlined />,
      label: <Link to="/workflows">工作流</Link>,
    },
    {
      key: '/functions',
      icon: <CodeOutlined />,
      label: <Link to="/functions">自定义组件</Link>,
    },
  ];

  const isFullPage = location.pathname === '/' || location.pathname === '/workflows' || location.pathname.startsWith('/workflow/edit');

  return (
    <Layout style={{ minHeight: '100vh' }}>
      <Sider collapsible style={{ background: '#1677ff' }}>
        <Menu
          theme="dark"
          selectedKeys={[location.pathname]}
          mode="inline"
          items={menuItems}
        />
      </Sider>
      <Layout className="site-layout">
        <Header className="site-layout-background" style={{ padding: '0 24px', display: 'flex', alignItems: 'center' }}>
          <Title level={3} style={{ margin: 0 }}>极简任务调度平台</Title>
        </Header>
        <Content style={isFullPage ? { height: '100%', padding: 0, margin: 0 } : { margin: '16px' }}>
          <Routes>
            <Route path="/" element={<WelcomePage />} />
            <Route path="/dashboard" element={<DashboardPage />} />
            <Route path="/workflows" element={<HomePage />} />
            <Route path="/workflow/edit" element={<WorkflowEditorPage />} />
            <Route path="/workflow/edit/:workflow_uuid" element={<WorkflowEditorPage />} />
            <Route path="/workflow/:workflow_uuid/history" element={<WorkflowHistoryPage />} />
            <Route path="/project/:projectCode/workflow/:workflowCode" element={<WorkflowViewerPage />} />
            <Route path="/instances/:projectCode/:instanceId" element={<WorkflowInstanceDetailPage />} />
            <Route path="/functions" element={<DiyFunctionPage />} />
            <Route path="/functions/edit/:functionId" element={<PythonEditorPage />} />
          </Routes>
        </Content>
      </Layout>
    </Layout>
  );
};

const AppWrapper: React.FC = () => (
  <ConfigProvider
    locale={zhCN}
    theme={{
      token: {
        colorPrimary: '#1677ff',
        colorLink: '#1677ff',
        colorLinkHover: '#4096ff',
        colorLinkActive: '#0958d9',
      },
      components: {
        Menu: {
          darkItemBg: '#1677ff',
          darkItemColor: 'rgba(255, 255, 255, 0.85)',
          darkItemHoverColor: '#ffffff',
          darkItemSelectedColor: '#ffffff',
          darkItemSelectedBg: '#096dd9',
        },
      },
    }}
  >
    <Router>
      <AntApp>
        <App />
      </AntApp>
    </Router>
  </ConfigProvider>
);

export default AppWrapper;

// frontend-vue/src/App.vue
<template>
  <a-config-provider
    :locale="zhCN"
    :theme="{
      token: {
        colorPrimary: '#1677ff',
        colorLink: '#1677ff',
        colorLinkHover: '#4096ff',
        colorLinkActive: '#0958d9',
      },
      components: {
        Menu: {
          darkItemBg: '#1677ff',
          darkItemColor: 'rgba(255, 255, 255, 0.85)',
          darkItemHoverColor: '#ffffff',
          darkItemSelectedColor: '#ffffff',
          darkItemSelectedBg: '#096dd9',
        },
      },
    }"
  >
    <a-layout style="min-height: 100vh">
      <a-sider collapsible style="background: #1677ff">
        <a-menu
          theme="dark"
          :selectedKeys="[$route.path]"
          mode="inline"
          :items="menuItems"
        />
      </a-sider>
      <a-layout class="site-layout">
        <a-header class="site-layout-background" style="padding: 0 24px; display: flex; align-items: center;">
          <h3 style="margin: 0; color: #fff;">极简任务调度平台</h3>
        </a-header>
        <a-content :style="isFullPage ? { height: '100%', padding: 0, margin: 0 } : { margin: '16px' }">
          <router-view />
        </a-content>
      </a-layout>
    </a-layout>
  </a-config-provider>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useRoute } from 'vue-router';
import { useMenu } from './hooks/useMenu';
import zhCN from 'ant-design-vue/es/locale/zh_CN';

const route = useRoute();
const { menuItems } = useMenu();

const isFullPage = computed(() => {
  return route.path === '/' || route.path === '/workflows' || route.path.startsWith('/workflow/edit');
});
</script>

<style>
.site-layout .site-layout-background {
  background: #1677ff;
}
</style>
