// frontend/src/pages/HomePage/index.tsx
import React, { useState, useEffect, useMemo } from 'react';
import {
  Table, Spin, Alert, Typography, Tag, Button, Space, Tooltip,
  App as AntApp,
  Select,
  Divider,
} from 'antd';
import { Link, useLocation } from 'react-router-dom';
import { useSelector, useDispatch } from 'react-redux';
import type { ColumnsType } from 'antd/es/table';
import { Workflow } from '../../types';
import { RootState, AppDispatch } from '../../store';
import {
  fetchProjects,
  fetchWorkflows,
  setSelectedProject,
  setIsRestoreModalOpen,
  setIsBackfillModalOpen,
} from '../../store/slices/homeSlice';
import api from '../../api';
import RestoreWorkflowModal from '../../components/RestoreWorkflowModal';
import BackfillModal from '../../components/BackfillModal';
import CreateProjectModal from './components/CreateProjectModal';
import '../../components/TaskNode'; // Register custom node
import { ActionButtons } from './components/ActionButtons';

const { Title } = Typography;



const HomePage: React.FC = () => {
  const { message } = AntApp.useApp();
  const location = useLocation();
  const dispatch: AppDispatch = useDispatch();
  const {
    workflows,
    loading,
    error,
    projects,
    selectedProject,
    isRestoreModalOpen,
    isBackfillModalOpen,
    selectedWorkflow,
  } = useSelector((state: RootState) => state.home);
  const [isCreateProjectModalOpen, setIsCreateProjectModalOpen] = useState(false);

  useEffect(() => {
    dispatch(fetchProjects());
    dispatch(fetchWorkflows());
  }, [dispatch, location]);


  const columns: ColumnsType<Workflow> = useMemo(() => [
    {
      title: '项目',
      dataIndex: 'projectName',
      key: 'projectName',
    },
    {
      title: '工作流名称',
      dataIndex: 'name',
      key: 'name',
    },
    {
      title: '定时设置',
      dataIndex: 'schedule_human_readable',
      key: 'schedule_human_readable',
      render: (text: string, record: Workflow) => (
        <Tooltip title={record.schedule_text}>
          <span>{text || '-'}</span>
        </Tooltip>
      ),
    },
    {
      title: '状态',
      dataIndex: 'releaseState',
      key: 'releaseState',
      render: (state: Workflow['releaseState'], record: Workflow) => {
        if (state === 'MODIFIED') {
          return <Tag color="processing">待同步</Tag>;
        }

        let color = 'default';
        let text = state;
        if (state === 'ONLINE') {
          color = 'green';
          text = '在线' as any;
        } else if (state === 'OFFLINE') {
          color = 'volcano';
          text = '离线' as any;
        } else if (state === 'UNSUBMITTED') {
          color = 'gold';
          text = '待提交' as any;
        }
        return <Tag color={color} key={state}>{text}</Tag>;
      },
    },
    {
      title: '最后更新时间',
      dataIndex: 'updateTime',
      key: 'updateTime',
      render: (time: string | number) => {
        if (typeof time === 'number') {
          return new Date(time * 1000).toLocaleString();
        }
        return new Date(time).toLocaleString();
      },
    },
    {
      title: '操作',
      key: 'actions',
      render: (_, record: Workflow) => <ActionButtons record={record} />,
    },
  ], []);

  if (loading) {
    return <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100%' }}><Spin size="large" /></div>;
  }

  if (error) {
    return <Alert message="错误" description={error} type="error" showIcon />;
  }

  const filteredWorkflows = selectedProject && selectedProject !== 'all'
    ? workflows.filter(w => w.projectName === selectedProject)
    : workflows;

  return (
    <div style={{ padding: '24px', background: '#fff', borderRadius: '8px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}>
        <Title level={2} style={{ margin: 0 }}>所有工作流</Title>
        <Space>
          <Select
            allowClear
            placeholder="选择项目"
            style={{ width: 200 }}
            onChange={(value) => {
              if (value === 'create_new_project') {
                setIsCreateProjectModalOpen(true);
              } else {
                dispatch(setSelectedProject(value));
              }
            }}
            value={selectedProject || 'all'}
            dropdownRender={(menu) => (
              <>
                {menu}
                <Divider style={{ margin: '8px 0' }} />
                <Button type="link" onClick={() => setIsCreateProjectModalOpen(true)} style={{ width: '100%' }}>
                  新建项目
                </Button>
              </>
            )}
          >
            <Select.Option value="all">所有项目</Select.Option>
            {projects.map(p => (
              <Select.Option key={p.code} value={p.name}>
                <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                  <span>{p.name}</span>
                  <Button
                    type="text"
                    danger
                    size="small"
                    onClick={async (e) => {
                      e.stopPropagation();
                      try {
                        await api.delete(`/api/projects/${p.code}`);
                        message.success('项目删除成功');
                        dispatch(fetchProjects());
                      } catch (error) {
                        message.error('删除项目失败');
                      }
                    }}
                  >
                    X
                  </Button>
                </div>
              </Select.Option>
            ))}
          </Select>
          <Button onClick={() => dispatch(setIsRestoreModalOpen(true))}>恢复工作流</Button>
          <Link to={`/workflow/edit${selectedProject && selectedProject !== 'all' ? `?projectName=${selectedProject}&projectCode=${projects.find(p => p.name === selectedProject)?.code}` : ''}`}>
            <Button type="primary">新建工作流</Button>
          </Link>
        </Space>
      </div>
      <Table 
        columns={columns} 
        dataSource={filteredWorkflows} 
        rowKey="uuid" 
        bordered
      />
      <RestoreWorkflowModal
        open={isRestoreModalOpen}
        onCancel={() => dispatch(setIsRestoreModalOpen(false))}
        onRestored={() => {
          dispatch(setIsRestoreModalOpen(false));
          dispatch(fetchWorkflows());
        }}
      />
      <BackfillModal
        open={isBackfillModalOpen}
        workflow={selectedWorkflow}
        onCancel={() => dispatch(setIsBackfillModalOpen(false))}
        onSuccess={() => {
          dispatch(setIsBackfillModalOpen(false));
          dispatch(fetchWorkflows());
        }}
      />
      <CreateProjectModal
        open={isCreateProjectModalOpen}
        onCancel={() => setIsCreateProjectModalOpen(false)}
        onSuccess={() => {
          setIsCreateProjectModalOpen(false);
          dispatch(fetchProjects());
          dispatch(fetchWorkflows());
        }}
      />
    </div>
  );
};

export default HomePage;

// frontend-vue/src/pages/HomePage/index.vue
<template>
  <div style="display: flex; flex-direction: column; height: 100%; padding: 24px">
    <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 24px; flex-shrink: 0">
      <a-typography-title :level="2" style="margin: 0">所有工作流</a-typography-title>
      <a-space>
        <a-select
          allow-clear
          placeholder="选择项目"
          style="width: 200px"
          :value="selectedProject"
          @change="handleProjectChange"
        >
          <template #dropdownRender="{ menuNode }">
            <component :is="menuNode" />
            <a-divider style="margin: 8px 0" />
            <a-button type="link" @click="isCreateProjectModalOpen = true" style="width: 100%">
              新建项目
            </a-button>
          </template>
          <a-select-option value="all">所有项目</a-select-option>
          <a-select-option v-for="p in projects" :key="p.code" :value="p.code">
            <div style="display: flex; justify-content: space-between">
              <span>{{ p.name }}</span>
            </div>
          </a-select-option>
        </a-select>
        <a-button @click="store.commit('home/setIsRestoreModalOpen', true)">恢复工作流</a-button>
        <router-link :to="`/workflow/edit${selectedProject && selectedProject !== 'all' ? `?projectName=${projects.find(p => p.code === selectedProject)?.name}&projectCode=${selectedProject}` : ''}`">
          <a-button type="primary">新建工作流</a-button>
        </router-link>
      </a-space>
    </div>
    <div style="flex: 1 1 auto; overflow: hidden; display: flex; flexDirection: column">
      <a-spin :spinning="loading" size="large" style="width: 100%; height: 100%">
        <a-alert v-if="error" :message="error" type="error" show-icon />
        <a-table
          v-else
          :columns="columns"
          :data-source="filteredWorkflows"
          row-key="uuid"
          bordered
          :pagination="{ pageSize: 10 }"
          style="flex: 1 1 auto; overflow: hidden"
          :scroll="{ y: 'calc(100vh - 340px)' }"
        >
          <template #bodyCell="{ column, record }">
            <template v-if="column.key === 'schedule_human_readable'">
              <a-tooltip :title="record.schedule_text">
                <span>{{ record.schedule_human_readable || '-' }}</span>
              </a-tooltip>
            </template>
            <template v-if="column.key === 'releaseState'">
                <a-tag v-if="record.releaseState === 'MODIFIED'" color="processing">待同步</a-tag>
                <a-tag v-else-if="record.releaseState === 'ONLINE'" color="green">在线</a-tag>
                <a-tag v-else-if="record.releaseState === 'OFFLINE'" color="volcano">离线</a-tag>
                <a-tag v-else-if="record.releaseState === 'UNSUBMITTED'" color="gold">待提交</a-tag>
                <a-tag v-else color="default">{{ record.releaseState }}</a-tag>
            </template>
            <template v-if="column.key === 'updateTime'">
              {{ formatUpdateTime(record.updateTime) }}
            </template>
            <template v-if="column.key === 'actions'">
              <ActionButtons :record="record" />
            </template>
          </template>
        </a-table>
      </a-spin>
    </div>
    <RestoreWorkflowModal
      :open="isRestoreModalOpen"
      @cancel="store.commit('home/setIsRestoreModalOpen', false)"
      @restored="onRestored"
    />
    <BackfillModal
      :open="isBackfillModalOpen"
      :workflow="selectedWorkflow"
      @cancel="store.commit('home/setIsBackfillModalOpen', false)"
      @success="onBackfillSuccess"
    />
    <CreateProjectModal
      :open="isCreateProjectModalOpen"
      @cancel="isCreateProjectModalOpen = false"
      @success="onCreateProjectSuccess"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import { useStore } from 'vuex';
import type { ColumnsType } from 'ant-design-vue/es/table';
import { Workflow, Project } from '../../types';
import RestoreWorkflowModal from '../../components/RestoreWorkflowModal.vue';
import BackfillModal from '../../components/BackfillModal.vue';
import CreateProjectModal from './components/CreateProjectModal.vue';
import ActionButtons from './components/ActionButtons.vue';
import { State } from '../../store';

const store = useStore<State>();

const workflows = computed(() => store.state.home.workflows);
const projects = computed(() => store.state.home.projects);
const loading = computed(() => store.state.home.loading);
const error = computed(() => store.state.home.error);
const selectedProject = computed(() => store.state.home.selectedProject);
const isRestoreModalOpen = computed(() => store.state.home.isRestoreModalOpen);
const isBackfillModalOpen = computed(() => store.state.home.isBackfillModalOpen);
const selectedWorkflow = computed(() => store.state.home.selectedWorkflow);

const isCreateProjectModalOpen = ref(false);

onMounted(() => {
  store.dispatch('home/fetchProjects');
  store.dispatch('home/fetchWorkflows');
});

const columns: ColumnsType<Workflow> = [
  { title: '项目', dataIndex: 'projectName', key: 'projectName' },
  { title: '工作流名称', dataIndex: 'name', key: 'name' },
  { title: '定时设置', key: 'schedule_human_readable' },
  { title: '状态', key: 'releaseState' },
  { title: '最后更新时间', key: 'updateTime' },
  { title: '操作', key: 'actions' },
];

const filteredWorkflows = computed(() => {
  const sp = selectedProject.value;
  if (sp && sp !== 'all') {
    return workflows.value.filter((w: Workflow) =>
      w.projectCode === sp || w.releaseState === 'UNSUBMITTED' || w.releaseState === 'MODIFIED'
    );
  }
  return workflows.value;
});

const handleProjectChange = (value: any) => {
  store.commit('home/setSelectedProject', value);
};

const onRestored = () => {
  store.commit('home/setIsRestoreModalOpen', false);
  store.dispatch('home/fetchWorkflows');
};

const onBackfillSuccess = () => {
  store.commit('home/setIsBackfillModalOpen', false);
  store.dispatch('home/fetchWorkflows');
};

const onCreateProjectSuccess = () => {
  isCreateProjectModalOpen.value = false;
  store.dispatch('home/fetchProjects');
  store.dispatch('home/fetchWorkflows');
};

const formatUpdateTime = (time: string | number) => {
  if (!time) return '-';
  const date = new Date(typeof time === 'number' ? time * 1000 : time);
  return isNaN(date.getTime()) ? '-' : date.toLocaleString();
};
</script>
