// frontend-vue/src/pages/HomePage/index.vue
<template>
  <div style="display: flex; flex-direction: column; height: 100%; padding: 24px">
    <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 24px; flex-shrink: 0">
      <a-typography-title :level="2" style="margin: 0">所有工作流</a-typography-title>
      <a-space>
        <a-select
          allow-clear
          placeholder="选择项目"
          style="width: 200px"
          :value="selectedProject"
          @change="handleProjectChange"
        >
          <template #dropdownRender="{ menuNode }">
            <component :is="menuNode" />
            <a-divider style="margin: 8px 0" />
            <a-button type="link" @click="isCreateProjectModalOpen = true" style="width: 100%">
              新建项目
            </a-button>
          </template>
          <a-select-option value="all">所有项目</a-select-option>
          <a-select-option v-for="p in projects" :key="p.code" :value="p.code">
            <div style="display: flex; justify-content: space-between">
              <span>{{ p.name }}</span>
            </div>
          </a-select-option>
        </a-select>
        <a-button @click="isRestoreModalOpen = true">恢复工作流</a-button>
        <router-link :to="`/workflow/edit${selectedProject && selectedProject !== 'all' ? `?projectName=${projects.find(p => p.code === selectedProject)?.name}&projectCode=${selectedProject}` : ''}`">
          <a-button type="primary">新建工作流</a-button>
        </router-link>
      </a-space>
    </div>
    <div style="flex: 1 1 auto; overflow: hidden; display: flex; flexDirection: column">
      <a-spin :spinning="loading" size="large" style="width: 100%; height: 100%">
        <a-alert v-if="error" :message="error" type="error" show-icon />
        <a-table
          v-else
          :columns="columns"
          :data-source="filteredWorkflows"
          row-key="uuid"
          bordered
          :pagination="{ pageSize: 10 }"
          style="flex: 1 1 auto; overflow: hidden"
          :scroll="{ y: 'calc(100vh - 340px)' }"
        >
          <template #bodyCell="{ column, record }">
            <template v-if="column.key === 'schedule_human_readable'">
              <a-tooltip :title="record.schedule_text">
                <span>{{ record.schedule_human_readable || '-' }}</span>
              </a-tooltip>
            </template>
            <template v-if="column.key === 'releaseState'">
                <a-tag v-if="record.releaseState === 'MODIFIED'" color="processing">待同步</a-tag>
                <a-tag v-else-if="record.releaseState === 'ONLINE'" color="green">在线</a-tag>
                <a-tag v-else-if="record.releaseState === 'OFFLINE'" color="volcano">离线</a-tag>
                <a-tag v-else-if="record.releaseState === 'UNSUBMITTED'" color="gold">待提交</a-tag>
                <a-tag v-else color="default">{{ record.releaseState }}</a-tag>
            </template>
            <template v-if="column.key === 'updateTime'">
              {{ new Date(record.updateTime * 1000).toLocaleString() }}
            </template>
            <template v-if="column.key === 'actions'">
              <ActionButtons
                :record="record"
                @deleted="fetchWorkflows"
                @online="fetchWorkflows"
                @execute="openBackfillModal"
              />
            </template>
          </template>
        </a-table>
      </a-spin>
    </div>
    <RestoreWorkflowModal
      :open="isRestoreModalOpen"
      @cancel="isRestoreModalOpen = false"
      @restored="onRestored"
    />
    <BackfillModal
      :open="isBackfillModalOpen"
      :workflow="selectedWorkflow"
      @cancel="isBackfillModalOpen = false"
      @success="onBackfillSuccess"
    />
    <CreateProjectModal
      :open="isCreateProjectModalOpen"
      @cancel="isCreateProjectModalOpen = false"
      @success="onCreateProjectSuccess"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import { useRoute } from 'vue-router';
import { message } from 'ant-design-vue';
import type { ColumnsType } from 'ant-design-vue/es/table';
import { Workflow, Project } from '../../types';
import api from '../../api';
import RestoreWorkflowModal from '../../components/RestoreWorkflowModal.vue';
import BackfillModal from '../../components/BackfillModal.vue';
import CreateProjectModal from './components/CreateProjectModal.vue';
import ActionButtons from './components/ActionButtons.vue';

const route = useRoute();
const workflows = ref<Workflow[]>([]);
const projects = ref<Project[]>([]);
const loading = ref(false);
const error = ref<string | null>(null);
const selectedProject = ref<number | 'all'>('all');
const isRestoreModalOpen = ref(false);
const isBackfillModalOpen = ref(false);
const isCreateProjectModalOpen = ref(false);
const selectedWorkflow = ref<Workflow | null>(null);

const fetchProjects = async () => {
  try {
    const response = await api.get<Project[]>('/projects');
    projects.value = response;
  } catch (e) {
    message.error('获取项目列表失败');
  }
};

const fetchWorkflows = async () => {
  loading.value = true;
  error.value = null;
  try {
    const response = await api.get<Workflow[]>('/workflows');
    workflows.value = response;
  } catch (e) {
    error.value = '获取工作流列表失败';
    message.error('获取工作流列表失败');
  } finally {
    loading.value = false;
  }
};

onMounted(() => {
  fetchProjects();
  fetchWorkflows();
});

const columns: ColumnsType<Workflow> = [
  { title: '项目', dataIndex: 'projectName', key: 'projectName' },
  { title: '工作流名称', dataIndex: 'name', key: 'name' },
  { title: '定时设置', key: 'schedule_human_readable' },
  { title: '状态', key: 'releaseState' },
  { title: '最后更新时间', key: 'updateTime' },
  { title: '操作', key: 'actions' },
];

const filteredWorkflows = computed(() => {
  if (selectedProject.value && selectedProject.value !== 'all') {
    return workflows.value.filter(w =>
      w.projectCode === selectedProject.value || w.releaseState === 'UNSUBMITTED' || w.releaseState === 'MODIFIED'
    );
  }
  return workflows.value;
});

const handleProjectChange = (value: any) => {
  selectedProject.value = value;
};

const onRestored = () => {
  isRestoreModalOpen.value = false;
  fetchWorkflows();
};

const onBackfillSuccess = () => {
  isBackfillModalOpen.value = false;
  fetchWorkflows();
};

const onCreateProjectSuccess = () => {
  isCreateProjectModalOpen.value = false;
  fetchProjects();
  fetchWorkflows();
};

const openBackfillModal = (workflow: Workflow) => {
  selectedWorkflow.value = workflow;
  isBackfillModalOpen.value = true;
};
</script>

// frontend/src/pages/HomePage.tsx
import React, { useState, useEffect, useCallback, useMemo } from 'react';
import {
  Table, Spin, Alert, Typography, Tag, Button, Space, Tooltip,
  App as AntApp
} from 'antd';
import { Link, useLocation } from 'react-router-dom';
import type { ColumnsType } from 'antd/es/table';
import { Workflow } from '../types';
import api from '../api';
import RestoreWorkflowModal from '../components/RestoreWorkflowModal';

const { Title } = Typography;

interface ActionButtonsProps {
  record: Workflow;
  onDelete: (record: Workflow) => void;
  onSubmit: (record: Workflow) => void;
  onExecute: (record: Workflow) => void;
  onOnline: (record: Workflow) => void;
}

const ActionButtons: React.FC<ActionButtonsProps> = ({ record, onDelete, onSubmit, onExecute, onOnline }) => {
  const workflowUuid = record.uuid;

  const isModified = record.releaseState === 'ONLINE' && record.local_status === 'modified';

  return (
    <Space size="middle">
      {isModified ? (
        <Button type="primary" onClick={() => onOnline(record)}>同步</Button>
      ) : record.releaseState === 'ONLINE' ? (
        <Button type="primary" onClick={() => onExecute(record)}>立即执行</Button>
      ) : null}
      
      {record.releaseState === 'UNSUBMITTED' && (
        <Button type="primary" onClick={() => onSubmit(record)}>提交</Button>
      )}
      {record.releaseState === 'OFFLINE' && (
        <Button type="primary" onClick={() => onOnline(record)}>上线</Button>
      )}
      <Link to={`/workflow/edit/${workflowUuid}`}>编辑</Link>
      <Link to={`/workflow/${workflowUuid}/history`}>历史</Link>
      <Button type="link" danger onClick={() => onDelete(record)}>删除</Button>
    </Space>
  );
};

const HomePage: React.FC = () => {
  const { message } = AntApp.useApp();
  const location = useLocation();
  const [workflows, setWorkflows] = useState<Workflow[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const [isRestoreModalOpen, setIsRestoreModalOpen] = useState(false);

  const fetchWorkflows = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const combinedWorkflows = await api.get<Workflow[]>('/api/workflows/combined');
      setWorkflows(combinedWorkflows);
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'An unknown error occurred';
      setError(errorMessage);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchWorkflows();
  }, [fetchWorkflows, location]);

  const handleDelete = useCallback(async (record: Workflow) => {
    try {
      const params: { project_code?: number; workflow_code?: number } = {};
      // Only add DS-related codes if they exist and are valid.
      // `record.code` for local files is a string filename, so we must not send it.
      if (record.projectCode && typeof record.code === 'number') {
        params.project_code = record.projectCode;
        params.workflow_code = record.code;
      }

      await api.delete(`/api/workflow/${record.uuid}`, params);
      message.success('工作流删除成功。');
      fetchWorkflows();
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'An unknown error occurred';
      message.error(errorMessage);
    }
  }, [fetchWorkflows, message]);

  const handleSubmit = useCallback(async (record: Workflow) => {
    try {
      await api.post('/api/workflow/submit', { filename: record.code });
      message.success('工作流提交成功。');
      fetchWorkflows();
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'An unknown error occurred';
      message.error(errorMessage);
    }
  }, [fetchWorkflows, message]);

  const handleExecute = useCallback(async (record: Workflow) => {
    try {
      await api.post(`/api/ds/execute/${record.projectCode}/${record.code}`, {
        scheduleTime: ''
      });
      message.success('工作流执行成功启动。');
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'An unknown error occurred';
      message.error(errorMessage);
    }
  }, [message]);

  const handleOnline = useCallback(async (record: Workflow) => {
    try {
      await api.post(`/api/workflow/${record.uuid}/online`);
      message.success('工作流上线成功。');
      fetchWorkflows();
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'An unknown error occurred';
      message.error(errorMessage);
    }
  }, [fetchWorkflows, message]);

  const columns: ColumnsType<Workflow> = useMemo(() => [
    {
      title: '工作流名称',
      dataIndex: 'name',
      key: 'name',
    },
    {
      title: '定时设置',
      dataIndex: 'schedule_human_readable',
      key: 'schedule_human_readable',
      render: (text: string, record: Workflow) => (
        <Tooltip title={record.schedule_text}>
          <span>{text || '-'}</span>
        </Tooltip>
      ),
    },
    {
      title: '状态',
      dataIndex: 'releaseState',
      key: 'releaseState',
      render: (state: Workflow['releaseState'], record: Workflow) => {
        if (state === 'ONLINE' && record.local_status === 'modified') {
          return <Tag color="processing">待更新</Tag>;
        }

        let color = 'default';
        let text = state;
        if (state === 'ONLINE') {
          color = 'green';
          text = '在线' as any;
        } else if (state === 'OFFLINE') {
          color = 'volcano';
          text = '离线' as any;
        } else if (state === 'UNSUBMITTED') {
          color = 'gold';
          text = '待提交' as any;
        }
        return <Tag color={color} key={state}>{text}</Tag>;
      },
    },
    {
      title: '最后更新时间',
      dataIndex: 'updateTime',
      key: 'updateTime',
      render: (time: string | number) => {
        if (typeof time === 'number') {
          return new Date(time * 1000).toLocaleString();
        }
        // Assuming it's a date string from DS
        return new Date(time).toLocaleString();
      },
    },
    {
      title: '操作',
      key: 'actions',
      render: (_, record) => <ActionButtons record={record} onDelete={handleDelete} onSubmit={handleSubmit} onExecute={handleExecute} onOnline={handleOnline} />,
    },
  ], [handleDelete]);

  if (loading) {
    return <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100%' }}><Spin size="large" /></div>;
  }

  if (error) {
    return <Alert message="错误" description={error} type="error" showIcon />;
  }

  return (
    <div style={{ padding: '24px', background: '#fff', borderRadius: '8px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}>
        <Title level={2} style={{ margin: 0 }}>所有工作流</Title>
        <Space>
          <Button onClick={() => setIsRestoreModalOpen(true)}>恢复工作流</Button>
          <Link to="/workflow/edit">
            <Button type="primary">新建工作流</Button>
          </Link>
        </Space>
      </div>
      <Table 
        columns={columns} 
        dataSource={workflows} 
        rowKey="uuid" 
        bordered
      />
      <RestoreWorkflowModal
        open={isRestoreModalOpen}
        onCancel={() => setIsRestoreModalOpen(false)}
        onRestored={() => {
          setIsRestoreModalOpen(false);
          fetchWorkflows();
        }}
      />
    </div>
  );
};

export default HomePage;
